# Semana 4 — Taller práctico: funciones, modularización y GitHub

**Asignatura:** Análisis de Datos con Python  
**Tipo de evidencia:** Notebook con ejercicios resueltos + repositorio inicial en GitHub  

## Propósito del taller

Aplicar funciones, modularización básica, comprensión de listas y diccionarios, manejo de errores y buenas prácticas de programación en un caso sencillo de análisis de datos.

## Entregables

1. Notebook completo con los ejercicios resueltos.
2. Repositorio inicial en GitHub con estructura organizada.
3. Archivo `README.md` con descripción del repositorio.
4. Evidencia del enlace al repositorio en la última sección del notebook.

## Instrucciones

Complete las celdas marcadas con `TODO`.

In [1]:
# Cargue y observe aquí los datos.
import pandas as pd

df = pd.read_csv('/content/sample_data/mecatronics_dataset.csv')

df.head()

   time  temperature_C  vibration_g  current_A system_state
0     0      20.397371     0.709903   1.932482       normal
1     1      19.989382     0.638695   1.995546       normal
2     2      20.718098     0.508945   1.940743       normal
3     3      21.518244     0.402959   1.999154       normal
4     4      20.212251     0.604733   1.850520       normal

## Parte 1 — Función para convertir valores

Cree una función llamada `convertir_a_float(valor)` que intente convertir un valor a número decimal.

La función debe retornar:

- El número convertido, si la conversión es posible.
- `None`, si el valor no se puede convertir.

In [2]:
# TODO: cree la función convertir_a_float

def convertir_a_float(valor):
    try:
        return float(valor)
    except (ValueError, TypeError):
        return None

# Pruebas sugeridas
print(convertir_a_float("12.5"))
print(convertir_a_float("error"))
print(convertir_a_float(""))
print(convertir_a_float(None))

12.5
None
None
None

## Parte 2 — Función para calcular potencia

Cree una función llamada `calcular_potencia(voltaje, corriente)`.

La función debe:

- Retornar `None` si voltaje o corriente son `None`.
- Retornar `None` si voltaje o corriente son negativos.
- Retornar `voltaje * corriente` en los demás casos.

In [3]:
# TODO: cree la función calcular_potencia

def calcular_potencia(voltaje, corriente):
    if voltaje is None or corriente is None:
        return None
    if voltaje < 0 or corriente < 0:
        return None
    return voltaje * corriente

# Pruebas sugeridas
print(calcular_potencia(12, 2))
print(calcular_potencia(None, 2))
print(calcular_potencia(12, -1))

24
None
None

## Parte 3 — Función para clasificar temperatura

Cree una función llamada `clasificar_temperatura(temp)` con los siguientes criterios:

- Si `temp` es `None`: `"Dato inválido"`
- Si `temp < 40`: `"Normal"`
- Si `40 <= temp < 50`: `"Precaución"`
- Si `temp >= 50`: `"Alerta"`

In [4]:
# TODO: cree la función clasificar_temperatura

def clasificar_temperatura(temp):
    if temp is None:
        return "Dato inválido"
    elif temp < 40:
        return "Normal"
    elif temp < 50:
        return "Precaución"
    else:
        return "Alerta"

# Pruebas sugeridas
print(clasificar_temperatura(35))
print(clasificar_temperatura(45))
print(clasificar_temperatura(52))
print(clasificar_temperatura(None))

Normal
Precaución
Alerta
Dato inválido

## Parte 4 — Limpieza y procesamiento de registros

Procese la lista `registros_crudos` y cree una nueva lista llamada `registros_limpios`.

Cada registro limpio debe contener:

- `id`
- `voltaje`
- `corriente`
- `temperatura`
- `potencia`
- `estado_temperatura`

Use las funciones creadas.

In [8]:
registros_limpios = []

for registro in registros_crudos:
    voltaje = convertir_a_float(registro["voltaje"])
    corriente = convertir_a_float(registro["corriente"])
    temperatura = convertir_a_float(registro["temperatura"])

    registros_limpios.append({
        "id": registro["id"],
        "voltaje": voltaje,
        "corriente": corriente,
        "temperatura": temperatura,
        "potencia": calcular_potencia(voltaje, corriente),
        "estado_temperatura": clasificar_temperatura(temperatura)
    })

registros_limpios

[{'id': 0,
  'voltaje': None,
  'corriente': 1.9324821725025616,
  'temperatura': 20.397371322408983,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 1,
  'voltaje': None,
  'corriente': 1.9955462811794744,
  'temperatura': 19.98938189252972,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 2,
  'voltaje': None,
  'corriente': 1.9407431963770216,
  'temperatura': 20.718097501413723,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 3,
  'voltaje': None,
  'corriente': 1.9991538720301445,
  'temperatura': 21.51824391752364,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 4,
  'voltaje': None,
  'corriente': 1.8505201200913155,
  'temperatura': 20.212250770067197,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 5,
  'voltaje': None,
  'corriente': 2.0710982105453186,
  'temperatura': 20.311857517674795,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 6,
  'voltaje': None,
  'corriente': 2.059721346774741,
  'temperatura': 21.86193128885051,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 7,
  'voltaje': None,
  'corriente': 1.9876576785834703,
  'temperatura': 21.31166335654351,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 8,
  'voltaje': None,
  'corriente': 2.144979784186301,
  'temperatura': 20.42101152432327,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 9,
  'voltaje': None,
  'corriente': 2.182413075761058,
  'temperatura': 21.329195901997892,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 10,
  'voltaje': None,
  'corriente': 1.937402422601948,
  'temperatura': 20.62261249972533,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 11,
  'voltaje': None,
  'corriente': 2.031279223421964,
  'temperatura': 20.718564312548143,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 12,
  'voltaje': None,
  'corriente': 2.0399112677138653,
  'temperatura': 21.382082949388497,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 13,
  'voltaje': None,
  'corriente': 2.031979199900255,
  'temperatura': 19.75477856373454,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 14,
  'voltaje': None,
  'corriente': 2.2179210483599747,
  'temperatura': 20.001843976810143,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 15,
  'voltaje': None,
  'corriente': 2.1244450477039805,
  'temperatura': 21.02777100991392,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 16,
  'voltaje': None,
  'corriente': 2.126070481148329,
  'temperatura': 20.76256790681305,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 17,
  'voltaje': None,
  'corriente': 1.960660579377513,
  'temperatura': 21.91883332678029,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 18,
  'voltaje': None,
  'corriente': 2.232934545039433,
  'temperatura': 21.034951905958483,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 19,
  'voltaje': None,
  'corriente': 2.053624632002278,
  'temperatura': 20.72475938599668,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 20,
  'voltaje': None,
  'corriente': 2.1915042039475536,
  'temperatura': 23.11961072668049,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 21,
  'voltaje': None,
  'corriente': 2.2210029999671264,
  'temperatura': 21.85818122490862,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 22,
  'voltaje': None,
  'corriente': 2.336870811659005,
  'temperatura': 22.18371988908034,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 23,
  'voltaje': None,
  'corriente': 2.077239462111825,
  'temperatura': 21.079941985856838,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 24,
  'voltaje': None,
  'corriente': 1.9132556116877744,
  'temperatura': 21.87338969808727,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 25,
  'voltaje': None,
  'corriente': 2.240438010434181,
  'temperatura': 22.485865764788908,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 26,
  'voltaje': None,
  'corriente': 2.4087037000252374,
  'temperatura': 21.56360582728084,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 27,
  'voltaje': None,
  'corriente': 2.3588927081821884,
  'temperatura': 22.871238372942106,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 28,
  'voltaje': None,
  'corriente': 2.262048420635786,
  'temperatura': 22.17542003766937,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 29,
  'voltaje': None,
  'corriente': 2.197735422145771,
  'temperatura': 22.506764684124747,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 30,
  'voltaje': None,
  'corriente': 2.3331535551061,
  'temperatura': 22.34184707719166,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 31,
  'voltaje': None,
  'corriente': 2.160348465847411,
  'temperatura': 24.38699835029368,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 32,
  'voltaje': None,
  'corriente': 2.310314342878629,
  'temperatura': 22.97517942702161,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 33,
  'voltaje': None,
  'corriente': 2.317909223935093,
  'temperatura': 22.219415516702448,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 34,
  'voltaje': None,
  'corriente': 2.3777697992291023,
  'temperatura': 23.80200104977489,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 35,
  'voltaje': None,
  'corriente': 2.5517994976672345,
  'temperatura': 22.24441351621164,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 36,
  'voltaje': None,
  'corriente': 2.3188533225080445,
  'temperatura': 23.46401423586117,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 37,
  'voltaje': None,
  'corriente': 2.2321829443037102,
  'temperatura': 21.803703459036903,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 38,
  'voltaje': None,
  'corriente': 2.2836749532986658,
  'temperatura': 22.38205838643401,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 39,
  'voltaje': None,
  'corriente': 2.112159865136246,
  'temperatura': 23.67388608469735,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 40,
  'voltaje': None,
  'corriente': 2.222110057300088,
  'temperatura': 24.177553718493943,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 41,
  'voltaje': None,
  'corriente': 2.2528430920780376,
  'temperatura': 23.792823773586456,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 42,
  'voltaje': None,
  'corriente': 2.2432260792030787,
  'temperatura': 23.630696973943703,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 43,
  'voltaje': None,
  'corriente': 2.31240553647776,
  'temperatura': 23.548329858004955,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 44,
  'voltaje': None,
  'corriente': 2.216133027942297,
  'temperatura': 22.670876802200908,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 45,
  'voltaje': None,
  'corriente': 2.4113515627136635,
  'temperatura': 23.34075918142165,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 46,
  'voltaje': None,
  'corriente': 2.2998102097306097,
  'temperatura': 23.609497083414,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 47,
  'voltaje': None,
  'corriente': 2.299067409775858,
  'temperatura': 24.883488283000705,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 48,
  'voltaje': None,
  'corriente': 2.26708260926116,
  'temperatura': 24.37085247315976,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 49,
  'voltaje': None,
  'corriente': 2.3149326279699625,
  'temperatura': 22.742054728169663,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 50,
  'voltaje': None,
  'corriente': 2.381132213792293,
  'temperatura': 24.46662209955532,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 51,
  'voltaje': None,
  'corriente': 2.210786421564651,
  'temperatura': 23.95247428541376,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 52,
  'voltaje': None,
  'corriente': 2.2302343257074138,
  'temperatura': 23.770483535971927,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 53,
  'voltaje': None,
  'corriente': 2.263890993700954,
  'temperatura': 24.851118442797624,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 54,
  'voltaje': None,
  'corriente': 2.157567196916137,
  'temperatura': 25.234588652421497,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 55,
  'voltaje': None,
  'corriente': 2.2077946101551005,
  'temperatura': 25.201060895600133,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 56,
  'voltaje': None,
  'corriente': 2.239342533890844,
  'temperatura': 23.829128192304413,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 57,
  'voltaje': None,
  'corriente': 2.371328944377497,
  'temperatura': 24.29579757989844,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 58,
  'voltaje': None,
  'corriente': 2.30675616011048,
  'temperatura': 24.849026288981683,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 59,
  'voltaje': None,
  'corriente': 2.296157381411163,
  'temperatura': 25.40346616373799,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 60,
  'voltaje': None,
  'corriente': 2.357879024264502,
  'temperatura': 24.2768560395599,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 61,
  'voltaje': None,
  'corriente': 2.2547398159024814,
  'temperatura': 24.546969600264283,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 62,
  'voltaje': None,
  'corriente': 2.3029129662781576,
  'temperatura': 23.84385201804287,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 63,
  'voltaje': None,
  'corriente': 2.2486406347014123,
  'temperatura': 23.803486408688045,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 64,
  'voltaje': None,
  'corriente': 2.2803076638297464,
  'temperatura': 25.440099959361486,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 65,
  'voltaje': None,
  'corriente': 2.1900222398766296,
  'temperatura': 25.902782949942623,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 66,
  'voltaje': None,
  'corriente': 1.9986672053182344,
  'temperatura': 24.78596740332706,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 67,
  'voltaje': None,
  'corriente': 2.223102346586731,
  'temperatura': 25.670249026790216,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 68,
  'voltaje': None,
  'corriente': 2.3725236310052105,
  'temperatura': 25.17863183221469,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 69,
  'voltaje': None,
  'corriente': 2.3163331038771755,
  'temperatura': 24.3931718481777,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 70,
  'voltaje': None,
  'corriente': 2.3134655129806148,
  'temperatura': 25.21636513434903,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 71,
  'voltaje': None,
  'corriente': 2.333512031259993,
  'temperatura': 26.17368806743137,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 72,
  'voltaje': None,
  'corriente': 2.211504713261489,
  'temperatura': 24.92863090967047,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 73,
  'voltaje': None,
  'corriente': 2.2148853864452183,
  'temperatura': 26.221056741709425,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 74,
  'voltaje': None,
  'corriente': 2.1256866702043418,
  'temperatura': 22.883608139416403,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 75,
  'voltaje': None,
  'corriente': 2.147934357628482,
  'temperatura': 25.644996936520453,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 76,
  'voltaje': None,
  'corriente': 2.2330090694476885,
  'temperatura': 25.063188374468453,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 77,
  'voltaje': None,
  'corriente': 2.2835202471138105,
  'temperatura': 24.758423272654703,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 78,
  'voltaje': None,
  'corriente': 2.140705783978339,
  'temperatura': 25.07311722237824,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 79,
  'voltaje': None,
  'corriente': 2.100978275330148,
  'temperatura': 23.409733100812986,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 80,
  'voltaje': None,
  'corriente': 2.1372345838764035,
  'temperatura': 24.822130504937515,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 81,
  'voltaje': None,
  'corriente': 2.18833463896306,
  'temperatura': 25.279638774562017,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 82,
  'voltaje': None,
  'corriente': 1.9747182117663709,
  'temperatura': 26.17034714238908,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 83,
  'voltaje': None,
  'corriente': 1.8802430021915009,
  'temperatura': 24.56550377496377,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 84,
  'voltaje': None,
  'corriente': 2.0454427600976133,
  'temperatura': 24.323421128675825,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 85,
  'voltaje': None,
  'corriente': 1.968948897618941,
  'temperatura': 24.556918417394712,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 86,
  'voltaje': None,
  'corriente': 2.0306286914839538,
  'temperatura': 25.67677052418517,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 87,
  'voltaje': None,
  'corriente': 2.056996766882448,
  'temperatura': 25.19159678190552,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 88,
  'voltaje': None,
  'corriente': 2.016702302984964,
  'temperatura': 24.48696342267446,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 89,
  'voltaje': None,
  'corriente': 2.1974573297898035,
  'temperatura': 25.30159698053091,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 90,
  'voltaje': None,
  'corriente': 2.075010478878192,
  'temperatura': 24.94690019386941,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 91,
  'voltaje': None,
  'corriente': 2.0624618288069825,
  'temperatura': 25.620461636828598,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 92,
  'voltaje': None,
  'corriente': 2.0846774850208183,
  'temperatura': 24.25827250566036,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 93,
  'voltaje': None,
  'corriente': 1.8985908869519104,
  'temperatura': 24.53022669811636,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 94,
  'voltaje': None,
  'corriente': 2.106388946648018,
  'temperatura': 24.44919444885225,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 95,
  'voltaje': None,
  'corriente': 1.9849021556079032,
  'temperatura': 23.56068847993138,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 96,
  'voltaje': None,
  'corriente': 2.0495358186958472,
  'temperatura': 24.935123590078287,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 97,
  'voltaje': None,
  'corriente': 1.865330662624192,
  'temperatura': 24.871919287854915,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 98,
  'voltaje': None,
  'corriente': 1.807199672804624,
  'temperatura': 24.63014836925481,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 99,
  'voltaje': None,
  'corriente': 2.0344652575595283,
  'temperatura': 24.39952006970893,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 100,
  'voltaje': None,
  'corriente': 1.980470563747106,
  'temperatura': 23.41419054048808,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 101,
  'voltaje': None,
  'corriente': 1.8428412918547148,
  'temperatura': 24.167449699400848,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 102,
  'voltaje': None,
  'corriente': 1.8363713612644808,
  'temperatura': 24.185471641545483,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 103,
  'voltaje': None,
  'corriente': 2.026257542415476,
  'temperatura': 23.771714938702576,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 104,
  'voltaje': None,
  'corriente': 1.78524513365474,
  'temperatura': 24.236636328204774,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 105,
  'voltaje': None,
  'corriente': 2.05903232701871,
  'temperatura': 24.639287518696,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 106,
  'voltaje': None,
  'corriente': 1.7953985838962898,
  'temperatura': 25.773651128732805,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 107,
  'voltaje': None,
  'corriente': 1.9401227297426964,
  'temperatura': 24.351314408448697,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 108,
  'voltaje': None,
  'corriente': 1.8343820194366456,
  'temperatura': 24.362957616471625,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 109,
  'voltaje': None,
  'corriente': 1.918670433106364,
  'temperatura': 24.04096300549394,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 110,
  'voltaje': None,
  'corriente': 1.7952054852120771,
  'temperatura': 22.50746504685872,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 111,
  'voltaje': None,
  'corriente': 1.8247698671202224,
  'temperatura': 23.96161626082106,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 112,
  'voltaje': None,
  'corriente': 1.836749943265588,
  'temperatura': 23.969763793374923,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 113,
  'voltaje': None,
  'corriente': 1.7242340664577875,
  'temperatura': 25.82935700008886,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 114,
  'voltaje': None,
  'corriente': 1.890525067259197,
  'temperatura': 23.64051476907971,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 115,
  'voltaje': None,
  'corriente': 1.757315030497786,
  'temperatura': 23.96976393475049,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 116,
  'voltaje': None,
  'corriente': 1.7781827565883233,
  'temperatura': 23.633387804387063,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 117,
  'voltaje': None,
  'corriente': 1.6942352147839568,
  'temperatura': 22.657381535250007,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 118,
  'voltaje': None,
  'corriente': 1.53029342464759,
  'temperatura': 24.436312080462898,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 119,
  'voltaje': None,
  'corriente': 1.760517823042936,
  'temperatura': 24.0519213439341,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 120,
  'voltaje': None,
  'corriente': 2.014220793568913,
  'temperatura': 24.01014146039019,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 121,
  'voltaje': None,
  'corriente': 1.845010576443292,
  'temperatura': 22.57539604256021,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 122,
  'voltaje': None,
  'corriente': 1.7584743706341623,
  'temperatura': 24.34941044042073,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 123,
  'voltaje': None,
  'corriente': 1.7282277837598503,
  'temperatura': 22.02867229974564,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 124,
  'voltaje': None,
  'corriente': 1.751152647817447,
  'temperatura': 23.54135696406877,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 125,
  'voltaje': None,
  'corriente': 1.798286129345869,
  'temperatura': 24.74472522116777,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 126,
  'voltaje': None,
  'corriente': 1.6204459867450391,
  'temperatura': 22.119224187515854,
  'potencia': None,
  'estado_temperatura': 'Normal'},
 {'id': 127,
  'voltaje': None,

## Parte 5 — Comprensión de listas

Use comprensión de listas para obtener:

1. Lista de potencias válidas.
2. Lista de temperaturas válidas.
3. Lista de motores en alerta.

In [9]:
# TODO: use comprensión de listas

potencias_validas = [
    registro["potencia"]
    for registro in registros_limpios
    if registro["potencia"] is not None
]

temperaturas_validas = [
    registro["temperatura"]
    for registro in registros_limpios
    if registro["temperatura"] is not None
]

motores_alerta = [
    registro
    for registro in registros_limpios
    if registro["estado_temperatura"] == "Alerta"
]

print(potencias_validas)
print(temperaturas_validas)
print(motores_alerta)

[]
[20.397371322408983, 19.98938189252972, 20.718097501413723, 21.51824391752364, 20.212250770067197, 20.311857517674795, 21.86193128885051, 21.31166335654351, 20.42101152432327, 21.329195901997892, 20.62261249972533, 20.718564312548143, 21.382082949388497, 19.75477856373454, 20.001843976810143, 21.02777100991392, 20.76256790681305, 21.91883332678029, 21.034951905958483, 20.72475938599668, 23.11961072668049, 21.85818122490862, 22.18371988908034, 21.079941985856838, 21.87338969808727, 22.485865764788908, 21.56360582728084, 22.871238372942106, 22.17542003766937, 22.506764684124747, 22.34184707719166, 24.38699835029368, 22.97517942702161, 22.219415516702448, 23.80200104977489, 22.24441351621164, 23.46401423586117, 21.803703459036903, 22.38205838643401, 23.67388608469735, 24.177553718493943, 23.792823773586456, 23.630696973943703, 23.548329858004955, 22.670876802200908, 23.34075918142165, 23.609497083414, 24.883488283000705, 24.37085247315976, 22.742054728169663, 24.46662209955532, 23.95247428541376, 23.770483535971927, 24.851118442797624, 25.234588652421497, 25.201060895600133, 23.829128192304413, 24.29579757989844, 24.849026288981683, 25.40346616373799, 24.2768560395599, 24.546969600264283, 23.84385201804287, 23.803486408688045, 25.440099959361486, 25.902782949942623, 24.78596740332706, 25.670249026790216, 25.17863183221469, 24.3931718481777, 25.21636513434903, 26.17368806743137, 24.92863090967047, 26.221056741709425, 22.883608139416403, 25.644996936520453, 25.063188374468453, 24.758423272654703, 25.07311722237824, 23.409733100812986, 24.822130504937515, 25.279638774562017, 26.17034714238908, 24.56550377496377, 24.323421128675825, 24.556918417394712, 25.67677052418517, 25.19159678190552, 24.48696342267446, 25.30159698053091, 24.94690019386941, 25.620461636828598, 24.25827250566036, 24.53022669811636, 24.44919444885225, 23.56068847993138, 24.935123590078287, 24.871919287854915, 24.63014836925481, 24.39952006970893, 23.41419054048808, 24.167449699400848, 24.185471641545483, 23.771714938702576, 24.236636328204774, 24.639287518696, 25.773651128732805, 24.351314408448697, 24.362957616471625, 24.04096300549394, 22.50746504685872, 23.96161626082106, 23.969763793374923, 25.82935700008886, 23.64051476907971, 23.96976393475049, 23.633387804387063, 22.657381535250007, 24.436312080462898, 24.0519213439341, 24.01014146039019, 22.57539604256021, 24.34941044042073, 22.02867229974564, 23.54135696406877, 24.74472522116777, 22.119224187515854, 22.37674296856129, 22.826498274205747, 22.259894014485145, 21.33697611425441, 22.54615859190401, 21.55427010396236, 22.694830269159876, 21.491333835322312, 23.37684692518318, 21.419468214491097, 21.69677468152772, 22.512808971021013, 20.784130273358556, 21.85690869846283, 22.62610402451121, 20.19922016888518, 21.537136715908776, 21.501002983704293, 21.82170494349176, 20.10935749242312, 19.94478463314143, 21.320534591964684, 21.042039313423828, 20.90599432057604, 20.88362484275073, 19.963070154320217, 20.59331371653015, 20.542226565788518, 19.63642217774536, 21.60057448754629, 20.387029601311863, 18.95492566757261, 20.333253364380887, 18.92838394668024, 20.238032515639635, 20.435633494480378, 18.752799865859544, 20.080871567039324, 19.54149627083296, 19.770336003791293, 20.53189352144981, 18.720314105260805, 18.21623446502952, 18.010682946165428, 17.97322842041203, 18.46832707039088, 18.707649784338464, 18.561426698360343, 18.907830460780723, 18.16319672077994, 19.223072672017203, 17.75674602268755, 20.05364548585378, 18.28793166173774, 17.01244438072198, 16.753149770874398, 17.908491067610324, 17.2573832349607, 17.922019690731208, 17.6451348643124, 17.12510044937265, 16.423874036901562, 15.808536101212487, 16.58349858363279, 17.547349920062313, 16.95628128503462, 15.712476626505884, 16.772990078963137, 16.8694231078632, 15.782182607385067, 16.541752239136567, 16.3962751705603, 15.367728067014127, 16.502217411738982, 16.60001191727447, 16.954761458406956, 16.86986289284094, 14.864775762718123, 15.15835441274585, 16.263982345710073, 16.207981742978795, 16.155671144366966, 18.77420069097008, 16.098833546486592, 16.502422383002852, 16.31078236788462, 16.02408595261875, 15.207948301205697, 16.02634569264734, 14.761749034754004, 15.15324114584178, 14.918954877311178, 15.339171750568742, 17.093716483891228, 13.718397808680244, 15.733353499433026, 13.868234232214744, 14.756859591242582, 15.983509889248408, 15.143672749818792, 14.211915270137258, 14.485700772896374, 15.587431343886406, 14.44725167645897, 15.194491006354356, 15.049552163432583, 14.485579665877854, 16.71777765732384, 15.507518930033903, 13.380030749023792, 15.151069251744616, 14.47623678073322, 15.693370440032512, 14.385160365074636, 14.937133249080125, 15.444646036629804, 15.746977851364248, 14.109832237547028, 14.82013594820558, 14.72741310136554, 14.606295364676985, 16.56485989495583, 15.501958560261112, 14.196671463216273, 15.968991404141985, 16.963656079647063, 16.125026170447775, 14.118561144950302, 14.983539330068336, 16.423176546002964, 14.884069172196424, 15.84763726268521, 16.156468845602298, 14.841182344136769, 15.582838405505449, 13.08692454551937, 14.91163599875985, 15.582006769603389, 14.840436243308616, 17.200857809589074, 14.808723615398398, 15.660327891083892, 16.17807770638497, 17.289196193472954, 15.051725636398643, 17.196703937384907, 16.34161044383739, 15.6169347150591, 16.841981151558656, 16.70311389847314, 16.13664281761568, 16.74696139302683, 16.458495761229678, 16.93448068683939, 17.451554013366405, 18.27007680894606, 16.091624293923484, 18.87008394008017, 15.68490204739381, 17.209160592013315, 17.886326543200518, 17.726584078603516, 17.090748025418865, 17.51049130264539, 17.371598990245786, 17.38441213777765, 18.62634743614512, 18.323861268814767, 17.576288999640298, 18.943412100406388, 18.563397824408764, 19.062346864711, 19.01089436107092, 17.939726500267714, 18.25106771069008, 19.393857758427814, 19.38161099295497, 18.97432807104804, 19.183049385286544, 20.20982184055497, 18.81326017134004, 19.82330792940328, 19.3232343843774, 19.41040802333074, 20.563305120356688, 20.44447365314678, 20.534891558838613, 21.028456536757773, 20.100872575727955, 20.729594264165105, 20.035707256260626, 20.64302895345335, 20.37920316466294, 20.66034279624664, 21.15806697005752, 20.126287361129283, 22.553383951120782, 20.17291867030296, 20.10424905020889, 22.099525778540453, 21.903335175020462, 21.865760828526785, 21.965054769560773, 21.54790939928936, 20.93460871383789, 21.80710030818866, 21.29807318365223, 22.7125083343336, 21.90660369788128, 21.454879228280976, 21.948349612433617, 22.625102595308952, 21.93215906340132, 21.812790439239897, 22.751956381173294, 22.838396956601635, 22.32122931290461, 22.43322268500906, 23.07783877182711, 21.814720000213786, 21.927015870033653, 22.55680977460633, 23.03813310800519, 23.533659046072348, 24.539946201973947, 24.11917334209981, 23.377106062207247, 23.56045318647464, 22.84282170891913, 23.6977558501851, 23.54787562914916, 24.10170209922925, 23.244929847136397, 24.383816530638704, 25.25456788409813, 23.99979477239038, 24.46496373962833, 24.75084364361379, 23.931206725634155, 24.48321092494284, 24.36404317908089, 24.48040092660424, 23.830382164667427, 24.513148618465287, 24.93489224308228, 25.73854709039148, 25.38435646724576, 26.376946660244812, 24.076121833563256, 25.42157964546731, 24.902230566626223, 26.53733097517622, 24.16686753523873, 24.16782088641281, 24.38424066561985, 23.18684918728127, 24.485618412977203, 24.317210541114846, 25.061156198565968, 25.228594178443178, 26.46849228793979, 25.738273949848114, 24.524800109921408, 24.27398498979434, 25.390648736377845, 23.94332472712336, 26.465076461132764, 25.9418598036209, 24.619366187515094, 23.61860027199267, 26.064611404026657, 24.88029469893861, 25.950603990827258, 23.67124910608141, 24.4517528560854, 24.91793704015386, 24.93185033000553, 24.512779611338782, 25.34772900010343, 23.970030061459383, 24.68297058144729, 24.86393975362239, 25.14817637655765, 25.272944685869977, 23.76908518561796, 23.40478614089533, 25.61564478416743, 24.818943045312324, 23.912069939536224, 25.707743798728774, 24.51353830594385, 25.316844385465885, 24.3780801587042, 25.921592880346992, 25.624487240417583, 23.966575244143574, 24.88686907707149, 24.56813503922489, 25.08734080914333, 23.159501157220564, 24.41771293269882, 24.651495696073543, 22.33212700763596, 22.725378679237945, 21.97199789452201, 23.31781501112374, 24.035917836184574, 24.590928518638258, 23.374121974746732, 24.54221596605462, 22.05842405599092, 21.7217160041211, 22.96066680187316, 23.23183832361025, 22.81674137406008, 21.106117579615763, 22.604845323446348, 21.547565429200997, 23.040842321353452, 22.71134412353948, 21.57815574800247, 21.83002810083357, 21.30391645605768, 22.010449148390244, 22.733187225753426, 21.08818587233388, 22.18694658020592, 21.265732471518383, 20.961193545936887, 21.41478259386178, 20.57652795122101, 20.865555422215568, 20.253402237258538, 22.68622967683435, 21.04495966628116, 20.358860986538847, 20.991350445440645, 20.63150114534962, 20.44549643790873, 21.01426510945292, 21.02938838361145, 19.89926241639941, 19.76316039986796, 19.903835769545477, 18.182352781162173, 18.711739893309, 20.917425629028678, 21.04000428504565, 19.42501556604585, 19.98585454881281, 19.67416383275045, 21.78905301347921, 20.122662565128167, 19.026032020700487, 18.265645841250173, 17.64702119316025, 18.997476328158708, 18.13261809563127, 17.503393900267145, 18.027980239773527, 17.584623708682866, 19.70481901852642, 18.966319050706087, 18.161226240687064, 19.258889707273102, 18.044929085274248, 17.20291388042043, 19.020190501021972, 18.14344856607112, 16.794067940864938, 17.38408867743481, 16.74934519607342, 16.258100222968103, 18.020836483578464, 18.724070201697025, 15.99544662189864, 17.48359410319157, 16.432809364384735, 16.484946448523832, 16.323305051624853, 16.02988207997288, 16.685058029176677, 15.907988123789146, 16.716992022656157, 16.389714122304778, 16.169452210758188, 15.56672146422142, 15.764999916616828, 16.76588393184269, 16.498993991833345, 15.254465980327558, 16.055811298026047, 16.51889983806687, 14.525343429674631, 16.240288921428448, 15.221912577089006, 16.1566004745686, 15.039344063961622, 14.157615519610037, 14.252816393655475, 15.548425445706007, 15.674638591307197, 14.702123586722571, 15.896996858957868, 14.019298336576352, 15.25990257415568, 14.31008031088474, 14.72543962181862, 15.254743855702191, 14.50032384326833, 14.85476419099345, 15.943131936679771, 14.654217952720389, 15.763872539319657, 14.173102574335342, 15.484229795923447, 16.199135525205257, 13.0560407853593, 14.385302529091732, 15.475929589364608, 14.845282957707305, 15.300080189890798, 14.517418234453071, 15.069320797224805, 14.876949676101548, 15.93915894768013, 15.213909767010986, 15.287890800283488, 14.697735486082085, 14.648569506952574, 14.706009835240511, 15.382999110158584, 14.748003781634347, 15.335931239760544, 16.785710271293276, 15.845517452408902, 14.9129674094558, 16.161856339605016, 14.903443452072311, 13.630330645862331, 14.487183353488067, 13.831723469907326, 15.083719418910556, 15.418092075028262, 16.78477298279345, 15.747253283277082, 15.354324867767774, 16.238811760589975, 13.853830879351548, 15.860433449946065, 16.33956780104208, 14.592651284495997, 16.744857886434676, 16.156654151151987, 15.611274669658563, 16.509001013200802, 17.880199162592103, 16.271581725993624, 16.3886585494451, 15.888110635600256, 15.64273884482146, 17.055368884022222, 15.776162572242924, 16.589627565889902, 16.222980565781825, 17.06238024299664, 17.02154420300494, 17.661362721478824, 16.501301319731038, 16.77263439633835, 16.285947823815242, 16.79512101764964, 17.535132589173482, 17.922726303314107, 16.664319475980903, 18.18369194139973, 18.65947772597645, 17.993645575819826, 19.253199327373448, 17.222495607083236, 16.93643085319026, 16.60063317677203, 19.31269011504097, 18.7323461138991, 18.258101209736573, 18.62093815495917, 17.59160751682788, 20.54423901951504, 18.787217988751173, 18.8680869322385, 19.45840220435968, 19.36026296879152, 19.252639285093117, 18.539599558402205, 19.647932062866666, 20.87544691606333, 20.545485358202992, 20.8432329581798, 19.259417972099047, 18.97654615278615, 19.76753267356849, 20.01272707349269, 20.943498033169856, 18.81414353233383, 21.491658665533823, 20.241408061171345, 20.12595837329791, 19.75724159921008, 19.342274869607092, 21.42366532674993, 20.922445844469543, 19.930139856993183, 20.02397783459957, 20.888921366075596, 22.58981161478001, 21.143464761468294, 20.24462649095329, 21.3459705760212, 21.419193339890327, 19.57401512268678, 21.78154819848924, 21.732966152896108, 22.56664149433169, 23.58000006008948, 23.092405683360766, 22.065484750619152, 21.48390481153646, 24.51539559796896, 22.59068206907346, 22.64003303286659, 22.694120286334257, 22.955333589358617, 22.763704166906, 22.50143796803193, 22.6028713900764, 23.09293079354885, 22.76192084769157, 22.702632671689525, 23.43299299313653, 23.217467455311077, 24.696875504305662, 21.443739725053284, 24.50712975293138, 24.69874760376035, 22.109641739782383, 23.55917103506505, 23.599602324819266, 22.8326209190772, 23.396668782685406, 23.1891457990239, 25.536476184551127, 24.938602089942005, 25.2610270291477, 24.87314672551707, 23.442875512085774, 23.97507018198865, 24.832997693984748, 23.508830907879982, 25.10017245568022, 24.378942100476134, 24.310946060404248, 25.217326708841977, 25.03986604978952, 24.429705414565262, 25.67807780810508, 23.91599873928142, 25.301921046847674, 25.310053122694825, 24.61240035552369, 25.143465365220184, 23.9022365682908, 25.660956341139524, 24.79045168472651, 24.53485836205912, 25.80492639506553, 24.41294007648643, 23.858351506694152, 23.746528738080112, 25.4813549048161, 23.97491977642516, 26.40381528004485, 23.333153158877288, 26.35257911851753, 25.158947237343902, 24.9054860270106, 24.537651423815447, 25.281636393136264, 24.918975683269554, 25.816501326986284, 25.008044838321705, 25.01774042704746, 24.58548661228472, 24.807746761721457, 25.07453029786004, 23.433208539492394, 23.69392881352004, 25.33631339678139, 24.84572282479741, 24.527288608541276, 24.652797499618543, 24.87783563469696, 24.127842596622816, 23.89506283166932, 24.630632064780663, 23.645717364629515, 24.7077062101222, 22.96997315780116, 25.10456782843604, 24.606812141645108, 24.379357343025, 24.904815984827017, 25.393524984973084, 24.813499309126065, 22.468560951811263, 22.85527939166773, 23.315215206411967, 23.770546035088884, 24.096903718364224, 23.033811697037105, 23.69400469020492, 22.869051674553116, 22.91152122295737, 22.20142378394391, 22.51285260389686, 22.093477523327245, 22.31624272472049, 23.86073214843181, 22.17796989687578, 24.96189000016985, 23.167991653703226, 22.83744991869712, 21.918062685791664, 23.0791228388248, 21.971483183278774, 22.44174704000512, 24.30341493850316, 22.088805398855435, 22.994511757958268, 21.421161725552352, 21.863528387281587, 23.215219419761716, 21.20334558901347, 23.060536460669447, 22.08179333209289, 20.970026315963835, 21.829765899912804, 22.0051937221264, 21.62741774225222, 19.77615763377662, 20.352582385040048, 20.63785822887648, 20.67757306754528, 21.134609324277307, 20.680929062243823, 19.37097388966848, 20.643713078686588, 20.728192997962328, 20.58763047736914, 20.904440499373383, 20.60695551663748, 20.207187802530168, 19.68380117649852, 18.31135902840488, 19.88416032416766, 19.60713767980942, 19.55899597858713, 18.221342724986183, 18.279207923396516, 19.888229375795376, 18.916098611888675, 19.395399823593145, 18.7757704022837, 18.68033578575477, 19.311110461455478, 18.0521759640573, 18.447050672975628, 17.906128041898885, 17.834835110060954, 17.842305215305043, 18.17532487082337, 17.523394821782585, 18.82061189976713, 17.01080800580841, 17.488392752678585, 17.198446254290406, 18.62113431619129, 17.535131283093772, 18.11874735668985, 16.021290345136528, 17.340961842052256, 17.757758284692727, 17.03179439760675, 17.739478636895416, 16.395635828179966, 17.86059296265066, 18.497188642077457, 16.29409115489445, 16.155618055847146, 17.603780869848546, 17.635207743158592, 15.885190074881722, 15.900735272433025, 15.946368864462038, 15.032679198501086, 15.311317758186846, 15.182507861575996, 15.312769200786118, 15.842075263644771, 16.001662895930483, 17.000833668246923, 14.909587975662628, 16.445283695587328, 15.437926081772456, 15.522593864370531, 16.056843175662195, 14.57542585971003, 15.737957667196136, 15.525445157254811, 15.748340947534675, 15.549669583182894, 17.24840211542525, 14.741683623856972, 14.79669084146608, 14.694500119462404, 14.72207771130014, 14.63192992260026, 16.070376266524264, 16.234842126929234, 14.623077939592202, 14.39699482656954, 15.425190823081769, 14.593439746091391, 15.530709285795288, 15.17783808647306, 13.79603394966834, 16.241759456356892, 16.43758191866215, 14.509772894124996, 14.690966596686156, 15.232943637548711, 15.276938470153173, 15.54332635374051, 16.633765801233874, 14.895145315651597, 14.411151482026648, 13.961400093543368, 14.4971516343076, 15.074401454427893, 16.557516263473442, 14.730699060332626, 15.348678607799911, 15.183302152855395, 16.175868671462375, 17.277323451108277, 14.86360357551897, 14.931152741027104, 16.19430955380227, 15.9426269467331, 16.914453611632904, 15.94602939937844, 15.23506066354046, 16.040416628342655, 16.502026839674336, 16.320374847529987, 16.120467801368278, 16.620361885496262, 16.75652529823149, 16.982554219506564, 16.453182351764273, 15.85953365246867, 16.171215396228796, 17.08124636025527, 15.526238922764968, 16.54000241323994, 15.997170947294986, 16.40309130054634, 17.472558290884304, 16.673797447758638, 16.630580410747417, 15.579421820429136, 17.339518179896817, 17.33541421628649, 18.627414541155627, 16.72961330000618, 17.231390900880214, 17.33698986899078, 18.48200279777089, 17.227472946853247, 17.611674272482613, 17.96056652110225, 17.710339139915224, 17.291683024555404, 17.892820422005165, 18.68607728952833, 17.096452214339173, 18.115365663867355, 17.54101512076409, 19.15003045399361, 17.06904738382492, 17.934748125038066, 18.778591022294645, 19.82478591610052, 18.61588268861273, 18.320972069962338, 20.36720007157391, 17.801461095457103, 17.298841287508196, 19.508288282878613, 18.85336149144692, 18.537044753435985, 20.02000068017593, 19.74785927505135, 19.201237847698984, 18.72807827667145, 20.5502077695315, 20.47238206184069, 19.9728787519318, 21.62950647619405, 19.396045625973134, 19.131509019958276, 19.8980776514867, 20.514629609379288, 20.845043864972723, 20.556397202029697, 21.129744363898748, 19.94524327699668, 22.19948269196232, 21.076328483866945, 22.133007705185303, 21.60997727845684, 21.797291237127425, 21.98322141006676, 21.98048241530225, 22.23075285199351, 22.873469138046215, 22.06021248483164, 22.562285817424787, 22.014583511683902, 23.328920574224043, 21.72529699327106, 23.795840680185577, 22.41069746834712, 21.38496214521282, 22.71781235771711, 22.155188002030084, 23.456164693691164, 22.34405777472151, 22.59057089068649, 21.516066763841582, 22.744824965167787, 21.24529460464641, 21.993730135775223, 23.94433415061309, 24.038458227261344, 23.82263594263516, 22.77974791004269, 23.58479738681862, 23.688272949362773, 22.831175325406708, 25.0257947175735, 24.588645728562557, 23.772109726444818, 24.030935406335537, 24.23507493389357, 22.49229545196089, 23.983605881518336, 23.68975234660661, 23.4863416151314, 24.113340268899574, 25.825217374489853, 24.946835323057982, 24.022537117960024, 24.98107407821477]
[]

## Parte 6 — Comprensión de diccionarios

Cree un diccionario llamado `estado_por_motor` donde:

- La clave sea el `id` del motor.
- El valor sea el `estado_temperatura`.

In [10]:
# TODO: cree el diccionario estado_por_motor

estado_por_motor = {
    registro["id"]: registro["estado_temperatura"]
    for registro in registros_limpios
}

estado_por_motor

{0: 'Normal',
 1: 'Normal',
 2: 'Normal',
 3: 'Normal',
 4: 'Normal',
 5: 'Normal',
 6: 'Normal',
 7: 'Normal',
 8: 'Normal',
 9: 'Normal',
 10: 'Normal',
 11: 'Normal',
 12: 'Normal',
 13: 'Normal',
 14: 'Normal',
 15: 'Normal',
 16: 'Normal',
 17: 'Normal',
 18: 'Normal',
 19: 'Normal',
 20: 'Normal',
 21: 'Normal',
 22: 'Normal',
 23: 'Normal',
 24: 'Normal',
 25: 'Normal',
 26: 'Normal',
 27: 'Normal',
 28: 'Normal',
 29: 'Normal',
 30: 'Normal',
 31: 'Normal',
 32: 'Normal',
 33: 'Normal',
 34: 'Normal',
 35: 'Normal',
 36: 'Normal',
 37: 'Normal',
 38: 'Normal',
 39: 'Normal',
 40: 'Normal',
 41: 'Normal',
 42: 'Normal',
 43: 'Normal',
 44: 'Normal',
 45: 'Normal',
 46: 'Normal',
 47: 'Normal',
 48: 'Normal',
 49: 'Normal',
 50: 'Normal',
 51: 'Normal',
 52: 'Normal',
 53: 'Normal',
 54: 'Normal',
 55: 'Normal',
 56: 'Normal',
 57: 'Normal',
 58: 'Normal',
 59: 'Normal',
 60: 'Normal',
 61: 'Normal',
 62: 'Normal',
 63: 'Normal',
 64: 'Normal',
 65: 'Normal',
 66: 'Normal',
 67: 'Normal',
 68: 'Normal',
 69: 'Normal',
 70: 'Normal',
 71: 'Normal',
 72: 'Normal',
 73: 'Normal',
 74: 'Normal',
 75: 'Normal',
 76: 'Normal',
 77: 'Normal',
 78: 'Normal',
 79: 'Normal',
 80: 'Normal',
 81: 'Normal',
 82: 'Normal',
 83: 'Normal',
 84: 'Normal',
 85: 'Normal',
 86: 'Normal',
 87: 'Normal',
 88: 'Normal',
 89: 'Normal',
 90: 'Normal',
 91: 'Normal',
 92: 'Normal',
 93: 'Normal',
 94: 'Normal',
 95: 'Normal',
 96: 'Normal',
 97: 'Normal',
 98: 'Normal',
 99: 'Normal',
 100: 'Normal',
 101: 'Normal',
 102: 'Normal',
 103: 'Normal',
 104: 'Normal',
 105: 'Normal',
 106: 'Normal',
 107: 'Normal',
 108: 'Normal',
 109: 'Normal',
 110: 'Normal',
 111: 'Normal',
 112: 'Normal',
 113: 'Normal',
 114: 'Normal',
 115: 'Normal',
 116: 'Normal',
 117: 'Normal',
 118: 'Normal',
 119: 'Normal',
 120: 'Normal',
 121: 'Normal',
 122: 'Normal',
 123: 'Normal',
 124: 'Normal',
 125: 'Normal',
 126: 'Normal',
 127: 'Normal',
 128: 'Normal',
 129: 'Normal',
 130: 'Normal',
 131: 'Normal',
 132: 'Normal',
 133: 'Normal',
 134: 'Normal',
 135: 'Normal',
 136: 'Normal',
 137: 'Normal',
 138: 'Normal',
 139: 'Normal',
 140: 'Normal',
 141: 'Normal',
 142: 'Normal',
 143: 'Normal',
 144: 'Normal',
 145: 'Normal',
 146: 'Normal',
 147: 'Normal',
 148: 'Normal',
 149: 'Normal',
 150: 'Normal',
 151: 'Normal',
 152: 'Normal',
 153: 'Normal',
 154: 'Normal',
 155: 'Normal',
 156: 'Normal',
 157: 'Normal',
 158: 'Normal',
 159: 'Normal',
 160: 'Normal',
 161: 'Normal',
 162: 'Normal',
 163: 'Normal',
 164: 'Normal',
 165: 'Normal',
 166: 'Normal',
 167: 'Normal',
 168: 'Normal',
 169: 'Normal',
 170: 'Normal',
 171: 'Normal',
 172: 'Normal',
 173: 'Normal',
 174: 'Normal',
 175: 'Normal',
 176: 'Normal',
 177: 'Normal',
 178: 'Normal',
 179: 'Normal',
 180: 'Normal',
 181: 'Normal',
 182: 'Normal',
 183: 'Normal',
 184: 'Normal',
 185: 'Normal',
 186: 'Normal',
 187: 'Normal',
 188: 'Normal',
 189: 'Normal',
 190: 'Normal',
 191: 'Normal',
 192: 'Normal',
 193: 'Normal',
 194: 'Normal',
 195: 'Normal',
 196: 'Normal',
 197: 'Normal',
 198: 'Normal',
 199: 'Normal',
 200: 'Normal',
 201: 'Normal',
 202: 'Normal',
 203: 'Normal',
 204: 'Normal',
 205: 'Normal',
 206: 'Normal',
 207: 'Normal',
 208: 'Normal',
 209: 'Normal',
 210: 'Normal',
 211: 'Normal',
 212: 'Normal',
 213: 'Normal',
 214: 'Normal',
 215: 'Normal',
 216: 'Normal',
 217: 'Normal',
 218: 'Normal',
 219: 'Normal',
 220: 'Normal',
 221: 'Normal',
 222: 'Normal',
 223: 'Normal',
 224: 'Normal',
 225: 'Normal',
 226: 'Normal',
 227: 'Normal',
 228: 'Normal',
 229: 'Normal',
 230: 'Normal',
 231: 'Normal',
 232: 'Normal',
 233: 'Normal',
 234: 'Normal',
 235: 'Normal',
 236: 'Normal',
 237: 'Normal',
 238: 'Normal',
 239: 'Normal',
 240: 'Normal',
 241: 'Normal',
 242: 'Normal',
 243: 'Normal',
 244: 'Normal',
 245: 'Normal',
 246: 'Normal',
 247: 'Normal',
 248: 'Normal',
 249: 'Normal',
 250: 'Normal',
 251: 'Normal',
 252: 'Normal',
 253: 'Normal',
 254: 'Normal',
 255: 'Normal',
 256: 'Normal',
 257: 'Normal',
 258: 'Normal',
 259: 'Normal',
 260: 'Normal',
 261: 'Normal',
 262: 'Normal',
 263: 'Normal',
 264: 'Normal',
 265: 'Normal',
 266: 'Normal',
 267: 'Normal',
 268: 'Normal',
 269: 'Normal',
 270: 'Normal',
 271: 'Normal',
 272: 'Normal',
 273: 'Normal',
 274: 'Normal',
 275: 'Normal',
 276: 'Normal',
 277: 'Normal',
 278: 'Normal',
 279: 'Normal',
 280: 'Normal',
 281: 'Normal',
 282: 'Normal',
 283: 'Normal',
 284: 'Normal',
 285: 'Normal',
 286: 'Normal',
 287: 'Normal',
 288: 'Normal',
 289: 'Normal',
 290: 'Normal',
 291: 'Normal',
 292: 'Normal',
 293: 'Normal',
 294: 'Normal',
 295: 'Normal',
 296: 'Normal',
 297: 'Normal',
 298: 'Normal',
 299: 'Normal',
 300: 'Normal',
 301: 'Normal',
 302: 'Normal',
 303: 'Normal',
 304: 'Normal',
 305: 'Normal',
 306: 'Normal',
 307: 'Normal',
 308: 'Normal',
 309: 'Normal',
 310: 'Normal',
 311: 'Normal',
 312: 'Normal',
 313: 'Normal',
 314: 'Normal',
 315: 'Normal',
 316: 'Normal',
 317: 'Normal',
 318: 'Normal',
 319: 'Normal',
 320: 'Normal',
 321: 'Normal',
 322: 'Normal',
 323: 'Normal',
 324: 'Normal',
 325: 'Normal',
 326: 'Normal',
 327: 'Normal',
 328: 'Normal',
 329: 'Normal',
 330: 'Normal',
 331: 'Normal',
 332: 'Normal',
 333: 'Normal',
 334: 'Normal',
 335: 'Normal',
 336: 'Normal',
 337: 'Normal',
 338: 'Normal',
 339: 'Normal',
 340: 'Normal',
 341: 'Normal',
 342: 'Normal',
 343: 'Normal',
 344: 'Normal',
 345: 'Normal',
 346: 'Normal',
 347: 'Normal',
 348: 'Normal',
 349: 'Normal',
 350: 'Normal',
 351: 'Normal',
 352: 'Normal',
 353: 'Normal',
 354: 'Normal',
 355: 'Normal',
 356: 'Normal',
 357: 'Normal',
 358: 'Normal',
 359: 'Normal',
 360: 'Normal',
 361: 'Normal',
 362: 'Normal',
 363: 'Normal',
 364: 'Normal',
 365: 'Normal',
 366: 'Normal',
 367: 'Normal',
 368: 'Normal',
 369: 'Normal',
 370: 'Normal',
 371: 'Normal',
 372: 'Normal',
 373: 'Normal',
 374: 'Normal',
 375: 'Normal',
 376: 'Normal',
 377: 'Normal',
 378: 'Normal',
 379: 'Normal',
 380: 'Normal',
 381: 'Normal',
 382: 'Normal',
 383: 'Normal',
 384: 'Normal',
 385: 'Normal',
 386: 'Normal',
 387: 'Normal',
 388: 'Normal',
 389: 'Normal',
 390: 'Normal',
 391: 'Normal',
 392: 'Normal',
 393: 'Normal',
 394: 'Normal',
 395: 'Normal',
 396: 'Normal',
 397: 'Normal',
 398: 'Normal',
 399: 'Normal',
 400: 'Normal',
 401: 'Normal',
 402: 'Normal',
 403: 'Normal',
 404: 'Normal',
 405: 'Normal',
 406: 'Normal',
 407: 'Normal',
 408: 'Normal',
 409: 'Normal',
 410: 'Normal',
 411: 'Normal',
 412: 'Normal',
 413: 'Normal',
 414: 'Normal',
 415: 'Normal',
 416: 'Normal',
 417: 'Normal',
 418: 'Normal',
 419: 'Normal',
 420: 'Normal',
 421: 'Normal',
 422: 'Normal',
 423: 'Normal',
 424: 'Normal',
 425: 'Normal',
 426: 'Normal',
 427: 'Normal',
 428: 'Normal',
 429: 'Normal',
 430: 'Normal',
 431: 'Normal',
 432: 'Normal',
 433: 'Normal',
 434: 'Normal',
 435: 'Normal',
 436: 'Normal',
 437: 'Normal',
 438: 'Normal',
 439: 'Normal',
 440: 'Normal',
 441: 'Normal',
 442: 'Normal',
 443: 'Normal',
 444: 'Normal',
 445: 'Normal',
 446: 'Normal',
 447: 'Normal',
 448: 'Normal',
 449: 'Normal',
 450: 'Normal',
 451: 'Normal',
 452: 'Normal',
 453: 'Normal',
 454: 'Normal',
 455: 'Normal',
 456: 'Normal',
 457: 'Normal',
 458: 'Normal',
 459: 'Normal',
 460: 'Normal',
 461: 'Normal',
 462: 'Normal',
 463: 'Normal',
 464: 'Normal',
 465: 'Normal',
 466: 'Normal',
 467: 'Normal',
 468: 'Normal',
 469: 'Normal',
 470: 'Normal',
 471: 'Normal',
 472: 'Normal',
 473: 'Normal',
 474: 'Normal',
 475: 'Normal',
 476: 'Normal',
 477: 'Normal',
 478: 'Normal',
 479: 'Normal',
 480: 'Normal',
 481: 'Normal',
 482: 'Normal',
 483: 'Normal',
 484: 'Normal',
 485: 'Normal',
 486: 'Normal',
 487: 'Normal',
 488: 'Normal',
 489: 'Normal',
 490: 'Normal',
 491: 'Normal',
 492: 'Normal',
 493: 'Normal',
 494: 'Normal',
 495: 'Normal',
 496: 'Normal',
 497: 'Normal',
 498: 'Normal',
 499: 'Normal',
 500: 'Normal',
 501: 'Normal',
 502: 'Normal',
 503: 'Normal',
 504: 'Normal',
 505: 'Normal',
 506: 'Normal',
 507: 'Normal',
 508: 'Normal',
 509: 'Normal',
 510: 'Normal',
 511: 'Normal',
 512: 'Normal',
 513: 'Normal',
 514: 'Normal',
 515: 'Normal',
 516: 'Normal',
 517: 'Normal',
 518: 'Normal',
 519: 'Normal',
 520: 'Normal',
 521: 'Normal',
 522: 'Normal',
 523: 'Normal',
 524: 'Normal',
 525: 'Normal',
 526: 'Normal',
 527: 'Normal',
 528: 'Normal',
 529: 'Normal',
 530: 'Normal',
 531: 'Normal',
 532: 'Normal',
 533: 'Normal',
 534: 'Normal',
 535: 'Normal',
 536: 'Normal',
 537: 'Normal',
 538: 'Normal',
 539: 'Normal',
 540: 'Normal',
 541: 'Normal',
 542: 'Normal',
 543: 'Normal',
 544: 'Normal',
 545: 'Normal',
 546: 'Normal',
 547: 'Normal',
 548: 'Normal',
 549: 'Normal',
 550: 'Normal',
 551: 'Normal',
 552: 'Normal',
 553: 'Normal',
 554: 'Normal',
 555: 'Normal',
 556: 'Normal',
 557: 'Normal',
 558: 'Normal',
 559: 'Normal',
 560: 'Normal',
 561: 'Normal',
 562: 'Normal',
 563: 'Normal',
 564: 'Normal',
 565: 'Normal',
 566: 'Normal',
 567: 'Normal',
 568: 'Normal',
 569: 'Normal',
 570: 'Normal',
 571: 'Normal',
 572: 'Normal',
 573: 'Normal',
 574: 'Normal',
 575: 'Normal',
 576: 'Normal',
 577: 'Normal',
 578: 'Normal',
 579: 'Normal',
 580: 'Normal',
 581: 'Normal',
 582: 'Normal',
 583: 'Normal',
 584: 'Normal',
 585: 'Normal',
 586: 'Normal',
 587: 'Normal',
 588: 'Normal',
 589: 'Normal',
 590: 'Normal',
 591: 'Normal',
 592: 'Normal',
 593: 'Normal',
 594: 'Normal',
 595: 'Normal',
 596: 'Normal',
 597: 'Normal',
 598: 'Normal',
 599: 'Normal',
 600: 'Normal',
 601: 'Normal',
 602: 'Normal',
 603: 'Normal',
 604: 'Normal',
 605: 'Normal',
 606: 'Normal',
 607: 'Normal',
 608: 'Normal',
 609: 'Normal',
 610: 'Normal',
 611: 'Normal',
 612: 'Normal',
 613: 'Normal',
 614: 'Normal',
 615: 'Normal',
 616: 'Normal',
 617: 'Normal',
 618: 'Normal',
 619: 'Normal',
 620: 'Normal',
 621: 'Normal',
 622: 'Normal',
 623: 'Normal',
 624: 'Normal',
 625: 'Normal',
 626: 'Normal',
 627: 'Normal',
 628: 'Normal',
 629: 'Normal',
 630: 'Normal',
 631: 'Normal',
 632: 'Normal',
 633: 'Normal',
 634: 'Normal',
 635: 'Normal',
 636: 'Normal',
 637: 'Normal',
 638: 'Normal',
 639: 'Normal',
 640: 'Normal',
 641: 'Normal',
 642: 'Normal',
 643: 'Normal',
 644: 'Normal',
 645: 'Normal',
 646: 'Normal',
 647: 'Normal',
 648: 'Normal',
 649: 'Normal',
 650: 'Normal',
 651: 'Normal',
 652: 'Normal',
 653: 'Normal',
 654: 'Normal',
 655: 'Normal',
 656: 'Normal',
 657: 'Normal',
 658: 'Normal',
 659: 'Normal',
 660: 'Normal',
 661: 'Normal',
 662: 'Normal',
 663: 'Normal',
 664: 'Normal',
 665: 'Normal',
 666: 'Normal',
 667: 'Normal',
 668: 'Normal',
 669: 'Normal',
 670: 'Normal',
 671: 'Normal',
 672: 'Normal',
 673: 'Normal',
 674: 'Normal',
 675: 'Normal',
 676: 'Normal',
 677: 'Normal',
 678: 'Normal',
 679: 'Normal',
 680: 'Normal',
 681: 'Normal',
 682: 'Normal',
 683: 'Normal',
 684: 'Normal',
 685: 'Normal',
 686: 'Normal',
 687: 'Normal',
 688: 'Normal',
 689: 'Normal',
 690: 'Normal',
 691: 'Normal',
 692: 'Normal',
 693: 'Normal',
 694: 'Normal',
 695: 'Normal',
 696: 'Normal',
 697: 'Normal',
 698: 'Normal',
 699: 'Normal',
 700: 'Normal',
 701: 'Normal',
 702: 'Normal',
 703: 'Normal',
 704: 'Normal',
 705: 'Normal',
 706: 'Normal',
 707: 'Normal',
 708: 'Normal',
 709: 'Normal',
 710: 'Normal',
 711: 'Normal',
 712: 'Normal',
 713: 'Normal',
 714: 'Normal',
 715: 'Normal',
 716: 'Normal',
 717: 'Normal',
 718: 'Normal',
 719: 'Normal',
 720: 'Normal',
 721: 'Normal',
 722: 'Normal',
 723: 'Normal',
 724: 'Normal',
 725: 'Normal',
 726: 'Normal',
 727: 'Normal',
 728: 'Normal',
 729: 'Normal',
 730: 'Normal',
 731: 'Normal',
 732: 'Normal',
 733: 'Normal',
 734: 'Normal',
 735: 'Normal',
 736: 'Normal',
 737: 'Normal',
 738: 'Normal',
 739: 'Normal',
 740: 'Normal',
 741: 'Normal',
 742: 'Normal',
 743: 'Normal',
 744: 'Normal',
 745: 'Normal',
 746: 'Normal',
 747: 'Normal',
 748: 'Normal',
 749: 'Normal',
 750: 'Normal',
 751: 'Normal',
 752: 'Normal',
 753: 'Normal',
 754: 'Normal',
 755: 'Normal',
 756: 'Normal',
 757: 'Normal',
 758: 'Normal',
 759: 'Normal',
 760: 'Normal',
 761: 'Normal',
 762: 'Normal',
 763: 'Normal',
 764: 'Normal',
 765: 'Normal',
 766: 'Normal',
 767: 'Normal',
 768: 'Normal',
 769: 'Normal',
 770: 'Normal',
 771: 'Normal',
 772: 'Normal',
 773: 'Normal',
 774: 'Normal',
 775: 'Normal',
 776: 'Normal',
 777: 'Normal',
 778: 'Normal',
 779: 'Normal',
 780: 'Normal',
 781: 'Normal',
 782: 'Normal',
 783: 'Normal',
 784: 'Normal',
 785: 'Normal',
 786: 'Normal',
 787: 'Normal',
 788: 'Normal',
 789: 'Normal',
 790: 'Normal',
 791: 'Normal',
 792: 'Normal',
 793: 'Normal',
 794: 'Normal',
 795: 'Normal',
 796: 'Normal',
 797: 'Normal',
 798: 'Normal',
 799: 'Normal',
 800: 'Normal',
 801: 'Normal',
 802: 'Normal',
 803: 'Normal',
 804: 'Normal',
 805: 'Normal',
 806: 'Normal',
 807: 'Normal',
 808: 'Normal',
 809: 'Normal',
 810: 'Normal',
 811: 'Normal',
 812: 'Normal',
 813: 'Normal',
 814: 'Normal',
 815: 'Normal',
 816: 'Normal',
 817: 'Normal',
 818: 'Normal',
 819: 'Normal',
 820: 'Normal',
 821: 'Normal',
 822: 'Normal',
 823: 'Normal',
 824: 'Normal',
 825: 'Normal',
 826: 'Normal',
 827: 'Normal',
 828: 'Normal',
 829: 'Normal',
 830: 'Normal',
 831: 'Normal',
 832: 'Normal',
 833: 'Normal',
 834: 'Normal',
 835: 'Normal',
 836: 'Normal',
 837: 'Normal',
 838: 'Normal',
 839: 'Normal',
 840: 'Normal',
 841: 'Normal',
 842: 'Normal',
 843: 'Normal',
 844: 'Normal',
 845: 'Normal',
 846: 'Normal',
 847: 'Normal',
 848: 'Normal',
 849: 'Normal',
 850: 'Normal',
 851: 'Normal',
 852: 'Normal',
 853: 'Normal',
 854: 'Normal',
 855: 'Normal',
 856: 'Normal',
 857: 'Normal',
 858: 'Normal',
 859: 'Normal',
 860: 'Normal',
 861: 'Normal',
 862: 'Normal',
 863: 'Normal',
 864: 'Normal',
 865: 'Normal',
 866: 'Normal',
 867: 'Normal',
 868: 'Normal',
 869: 'Normal',
 870: 'Normal',
 871: 'Normal',
 872: 'Normal',
 873: 'Normal',
 874: 'Normal',
 875: 'Normal',
 876: 'Normal',
 877: 'Normal',
 878: 'Normal',
 879: 'Normal',
 880: 'Normal',
 881: 'Normal',
 882: 'Normal',
 883: 'Normal',
 884: 'Normal',
 885: 'Normal',
 886: 'Normal',
 887: 'Normal',
 888: 'Normal',
 889: 'Normal',
 890: 'Normal',
 891: 'Normal',
 892: 'Normal',
 893: 'Normal',
 894: 'Normal',
 895: 'Normal',
 896: 'Normal',
 897: 'Normal',
 898: 'Normal',
 899: 'Normal',
 900: 'Normal',
 901: 'Normal',
 902: 'Normal',
 903: 'Normal',
 904: 'Normal',
 905: 'Normal',
 906: 'Normal',
 907: 'Normal',
 908: 'Normal',
 909: 'Normal',
 910: 'Normal',
 911: 'Normal',
 912: 'Normal',
 913: 'Normal',
 914: 'Normal',
 915: 'Normal',
 916: 'Normal',
 917: 'Normal',
 918: 'Normal',
 919: 'Normal',
 920: 'Normal',
 921: 'Normal',
 922: 'Normal',
 923: 'Normal',
 924: 'Normal',
 925: 'Normal',
 926: 'Normal',
 927: 'Normal',
 928: 'Normal',
 929: 'Normal',
 930: 'Normal',
 931: 'Normal',
 932: 'Normal',
 933: 'Normal',
 934: 'Normal',
 935: 'Normal',
 936: 'Normal',
 937: 'Normal',
 938: 'Normal',
 939: 'Normal',
 940: 'Normal',
 941: 'Normal',
 942: 'Normal',
 943: 'Normal',
 944: 'Normal',
 945: 'Normal',
 946: 'Normal',
 947: 'Normal',
 948: 'Normal',
 949: 'Normal',
 950: 'Normal',
 951: 'Normal',
 952: 'Normal',
 953: 'Normal',
 954: 'Normal',
 955: 'Normal',
 956: 'Normal',
 957: 'Normal',
 958: 'Normal',
 959: 'Normal',
 960: 'Normal',
 961: 'Normal',
 962: 'Normal',
 963: 'Normal',
 964: 'Normal',
 965: 'Normal',
 966: 'Normal',
 967: 'Normal',
 968: 'Normal',
 969: 'Normal',
 970: 'Normal',
 971: 'Normal',
 972: 'Normal',
 973: 'Normal',
 974: 'Normal',
 975: 'Normal',
 976: 'Normal',
 977: 'Normal',
 978: 'Normal',
 979: 'Normal',
 980: 'Normal',
 981: 'Normal',
 982: 'Normal',
 983: 'Normal',
 984: 'Normal',
 985: 'Normal',
 986: 'Normal',
 987: 'Normal',
 988: 'Normal',
 989: 'Normal',
 990: 'Normal',
 991: 'Normal',
 992: 'Normal',
 993: 'Normal',
 994: 'Normal',
 995: 'Normal',
 996: 'Normal',
 997: 'Normal',
 998: 'Normal',
 999: 'Normal'}

## Parte 7 — Resumen automático

Cree una función llamada `generar_resumen(registros)` que retorne un diccionario con:

- `total_registros`
- `registros_validos_potencia`
- `potencia_promedio`
- `temperatura_promedio`
- `cantidad_alertas`
- `cantidad_precauciones`
- `cantidad_normales`

In [11]:
# TODO: cree la función generar_resumen

def generar_resumen(registros):
    potencias = [
        registro["potencia"]
        for registro in registros
        if registro["potencia"] is not None
    ]

    temperaturas = [
        registro["temperatura"]
        for registro in registros
        if registro["temperatura"] is not None
    ]

    return {
        "total_registros": len(registros),
        "registros_validos_potencia": len(potencias),
        "potencia_promedio": sum(potencias) / len(potencias) if potencias else None,
        "temperatura_promedio": sum(temperaturas) / len(temperaturas) if temperaturas else None,
        "cantidad_alertas": sum(1 for registro in registros if registro["estado_temperatura"] == "Alerta"),
        "cantidad_precauciones": sum(1 for registro in registros if registro["estado_temperatura"] == "Precaución"),
        "cantidad_normales": sum(1 for registro in registros if registro["estado_temperatura"] == "Normal")
    }

resumen = generar_resumen(registros_limpios)
resumen

{'total_registros': 1000,
 'registros_validos_potencia': 0,
 'potencia_promedio': None,
 'temperatura_promedio': 20.161157833395325,
 'cantidad_alertas': 0,
 'cantidad_precauciones': 0,
 'cantidad_normales': 1000}

## Parte 8 — Visualización como tabla

Convierta `registros_limpios` en un `DataFrame` de Pandas.

In [12]:
import pandas as pd

# TODO: cree un DataFrame llamado df

df = pd.DataFrame(registros_limpios)

df

      id voltaje  corriente  temperatura potencia estado_temperatura
0      0    None   1.932482    20.397371     None             Normal
1      1    None   1.995546    19.989382     None             Normal
2      2    None   1.940743    20.718098     None             Normal
3      3    None   1.999154    21.518244     None             Normal
4      4    None   1.850520    20.212251     None             Normal
..   ...     ...        ...          ...      ...                ...
995  995    None   2.302904    24.113340     None             Normal
996  996    None   2.318978    25.825217     None             Normal
997  997    None   2.166748    24.946835     None             Normal
998  998    None   2.321739    24.022537     None             Normal
999  999    None   2.269873    24.981074     None             Normal

[1000 rows x 6 columns]

## Parte 9 — Buenas prácticas

Revise su notebook y verifique:

- Los nombres de variables son claros.
- Las funciones tienen una tarea específica.
- El código no está repetido innecesariamente.
- Las celdas están ejecutadas en orden.
- Hay explicaciones en texto.

## Parte 10 — Repositorio inicial en GitHub

Cree un repositorio en GitHub con el nombre:

**analisis-datos-python-apellido-nombre**

Estructura mínima esperada:

```text
analisis-datos-python-apellido-nombre/
│
├── README.md
├── requirements.txt
├── notebooks/
│   ├── semana_02_introduccion.ipynb
│   ├── semana_03_fundamentos_python.ipynb
│   └── semana_04_funciones_modularizacion.ipynb
│
├── data/
│   ├── raw/
│   └── processed/
│
├── src/
│   └── funciones.py
│
└── reports/
    └── figuras/
```

Enlace al repositorio:

Pegue aquí el enlace de su repositorio.

**Enlace al repositorio:**  
https://github.com/YesGz/analisis-datos-python-GomezR-Yesid

## Parte 11 — Reflexión final

Responda:

1. ¿Qué ventaja tuvo usar funciones en el procesamiento de los registros?
2. ¿Por qué es importante manejar errores antes de analizar datos?
3. ¿Qué función del taller considera más útil?
4. ¿Qué elemento del repositorio ayuda más a la reproducibilidad?

**Respuesta:**  
1. Usar funciones permitió organizar mejor el código y evitar repetir las mismas instrucciones varias veces. También hizo más fácil corregir o modificar una operación.
2. Porque los datos pueden tener valores incorrectos, vacíos o en formatos no válidos. Manejar estos errores evita que el programa falle y permite realizar un análisis más confiable.
3. Considero que la función convertir_a_float() fue una de las más útiles, porque permitió limpiar los datos y convertir correctamente los valores antes de utilizarlos en los cálculos.
4. l archivo requirements.txt ayuda mucho a la reproducibilidad porque indica las librerías necesarias para ejecutar el proyecto. Además, los notebooks permiten ver los pasos y el código utilizado durante el análisis.